name: ModReq
version: ${project.version}
description: ${project.description}
database: true

authors: [Travis Watkins, Deaygo Jarkko]
website: ${project.url}

main: nu.nerd.modreq.ModReq


commands:
  modreq:
    description: Make a request
    permission: modreq.request
    usage: |
           /<command> request: Make a request to the moderators
  check:
    description: Check request queue
    usage: |
           /<command> <p:#|#>: Check request queue or a specific request
  tp-id:
    description: Teleport to a request
    permission: modreq.teleport
    usage: |
           /<command> [#]: Teleport to a request
    aliases: [tpid]
  tpinfo:
    description: Teleport to and check a request
    permission: modreq.teleport
    usage: |
           /<command> [#]: Teleport to and check a request
    aliases: [tpi]
  tpc:
    description: Teleport to and claim a request
    permission: modreq.teleport
    usage: |
           /<command> [#]: Teleport to and claim a request
  claim:
    description: Claim a request
    permission: modreq.claim
    usage: |
           /<command> [#]: Claim a request
  unclaim:
    description: Remove your claim from a request
    permission: modreq.claim
    usage: |
           /<command> [#]: Unclaim a request
  done:
    description: Mark a request as completed
    usage: |
           /<command> <#> [message]: Close a request with an optional message
    aliases: [complete]
  reopen:
    description: Reopen a closed request
    permission: modreq.done
    usage: |
           /<command> <#>: Reopen closed request
  elevate:
    description: Set flag for admin on a request
    permission: modreq.mod
    usage: |
           /<command> <#>: Flag a request for an admin.
  mr-reset:
    description: Reset the modreq database.
    permission: modreq.cleardb
    usage: |
           /<command>: Reset the modreq database.
  mr-note:
    description: Add and remove notes to requests.
    permission: modreq.mod
    usage: |
           /<command> <add|remove> <#> <body|note-id>
  mr-upgrade:
    description: Upgrade the database
    permission: modreq.upgrade
    usage: |
           /<command>

permissions:
  modreq:
    description: Allow a player full access to request system
    children:
      modreq.mod:
        description: Allow a player to manage requests
        children:
          modreq.check:
            description: Allow a player to check the request queue
          modreq.claim:
            description: Allow a player to claim a request
          modreq.done:
            description: Allow a player to close a request
          modreq.teleport:
            description: Allow a player to teleport to the location a request was made
          modreq.notice:
            description: Allow a player to receive modreq broadcasts
  modreq.cleardb:
    description: Allow a player to clear the database.
  modreq.upgrade:
    description: Upgrade the database
  modreq.request:
    description: Allow a player to submit a request
    default: true
